AppBundle\Entity\Product:
    type: entity
    table: product
    indexes:
        fk_produck_type:
            columns:
                - product_type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
    manyToOne:
        productType:
            targetEntity: ProductType
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_type:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
